### ISSUE TITLE
Requesting additional example in fitting Markov Chain models

### ISSUE THREAD

**Issue by ha-ri-ni** [jmschrei/pomegranate#516] opened 2018-11-08 16:09 UTC
In the Markov chain tutorial https://github.com/jmschrei/pomegranate/blob/master/tutorials/B_Model_Tutorial_6_Markov_Chain.ipynb how would we fit the model to a new dataset if the sequences are words instead of characters (log_probability works, eg. 
![screen shot 2018-11-08 at 11 08 48 am](https://user-images.githubusercontent.com/29256234/48211065-b34a3180-e346-11e8-879c-9cd17a5f5ed3.png)

`clf.fit(['/bin/bash', 'bash,'])` gives  `KeyError: '/'`

**Comment by jmschrei** [comment] 2018-11-13 18:48
When you fit a Markov chain you need to pass in a list of sequences. The model interpreted what you passed in as the sequence '/bin/bash', meaning the first observation was '/', the next was 'b', the next was 'i', and so on. Try `clf.fit([['/bin/bash', 'bash']])` if you're trying to pass in a single sequence whose first element is '/bin/bash' and second element is 'bash'.

I'm currently working on revamping the tutorials, so I'll make sure to get to the Markov chain one soon.

**Comment by ha-ri-ni** [comment] 2018-11-14 16:16
great thanks! `clf.fit([['/bin/bash', 'bash']])` gives the following error

![screen shot 2018-11-14 at 11 15 18 am](https://user-images.githubusercontent.com/29256234/48495768-af168c00-e7fe-11e8-82ab-62f20ab12ad0.png)

**Comment by jmschrei** [comment] 2019-12-04 22:40
It looks like the keys '/bin/bash' and 'bash' were not keys in your conditional probability table. You must make sure that all the keys you will see are going to be in the original distribution or use the `from_samples` method. I'm going to close this for now, but if you still encounter issues please re-open and submit a minimally reproducing example so that I can help you further.

**Closed by jmschrei** 2019-12-04 22:40 UTC
