### ISSUE TITLE
Saving and loading models

### ISSUE THREAD

**Issue by FernandoBenayas** [jmschrei/pomegranate#468] opened 2018-07-09 11:19 UTC
Hello,

I have a json file generated by using the to_json method in BayesianNetwork. A snippet of this json file can be seen here:

"class" : "State",
            "weight" : 1.0,
            "distribution" : {
                "table" : [
                    [
                        "10",
                        "False",
                        "1.0"
                    ],
                    [
                        "10",
                        "First",
                        "0.0"

The problem is that when I load this json file using the from_json method to obtain the BayesianNetwork object I saved, this is the model generated:

 "class" : "State",
            "weight" : 1.0,
            "distribution" : {
                "table" : [
                    [
                        "10.0",
                        "False",
                        "1.0"
                    ],
                    [
                        "10.0",
                        "First",
                        "0.0"
As you can see, it turns "10" into "10.0"; I guess at some point it cast every string representing numbers to float. As a result, I can't use it to predict passing the same type of fields I used before I saved it.  

Can this be fixed, so I don't have to change the data I am using after I save and load the model?

**Comment by jmschrei** [comment] 2018-07-10 22:34
Howdy

Sorry you ran into that problem.  It looks like it's caused by an issue with the JSON package, but I can add it to my queue of things to look into. I'll let you know when I get to it!

**Comment by jmschrei** [comment] 2018-07-24 19:46
This issue should be resolved in the latest commit. Can you pull and see if it fixes your issue?

**Comment by jmschrei** [comment] 2018-07-25 06:42
Please re-open if you continue to encounter the issue.

**Closed by jmschrei** 2018-07-25 06:42 UTC
