### ISSUE TITLE
Great package but my BNs are very poor for prediction

### ISSUE THREAD

**Issue by ingjpal** [jmschrei/pomegranate#785] opened 2020-07-03 10:54 UTC
Hello Jacob, 

I've been using your package for a year now and it works like a charm ! However, for some weird reason, I'm getting very poor performance of my fitted networks (from samples, group variables, from structure, from weight sampling, over sampling and udersampling) and I have the impression this is because of my dataset. However, the dataset is quite large (16 variables with 81000 samples quite sparse). I evaluate the trained network by taking the dataset and removing one variable from all samples and then predicting it and estimating its confusion matrix. I was wondering if there is a way to impose a probability threshold so that for binary class prediction I can tell pomegranate to use this conditional instead of choosing the one with the highest probability ? Or is there a way to estimate if my dataset is the problem ? 

regards, 

Juan

**Comment by jmschrei** [comment] 2020-07-11 21:43
Howdy Juan

Thanks! If you'd like to impose your own probability cutoffs you should use the `predict_proba` method instead of the `predict` method. You will get a probability distribution over classes that way and can do with that whatever you'd like. I assume when you say that you removed one variable from all samples you mean that you removed the variable from the test data but kept it in the training data? I'm not sure how well you'd predict it otherwise.

As for debugging, there are a few options. The first is to inspect the learned model and see what types of relationships have been captured by the model by looking at `model.structure`. If the variable of interest has no parents, that might be a source of your poor performance, because the model isn't learning anything about how other variables connect to it. You might also consider building a more classic machine learning model, e.g. logistic regression, to get baseline performance. It's possible that predicting your variable of interest is simply a difficult task.

Let me know how those end up working out!

**Comment by jmschrei** [comment] 2020-07-11 21:44
I'm going to close this for now but please continue to respond here  if you have more questions or re-open if you find a bug.

**Closed by jmschrei** 2020-07-11 21:44 UTC
