### ISSUE TITLE
HMM fit: probability of unseen emissions going to 0

### ISSUE THREAD

**Issue by demodw** [jmschrei/pomegranate#241] opened 2017-04-03 15:22 UTC
Hi,

In the example sequence model at http://nbviewer.jupyter.org/github/jmschrei/yahmm/blob/master/examples/Global%20Sequence%20Alignment.ipynb, if I train with sequences that do not contain e.g. G, the emission probability of G drops to 0. In return, any future sequence that contains G has -inf likelihood of being generated by the model. This is even when adding a pseudo-count.

E.g.,
model.fit(['ATC', 'AAT', 'ATT', 'ATA'], algorithm='baum-welch', transition_pseudocount=1.0, use_pseudocount=True)
> Training improvement: 9.39574551379
> Training improvement: -0.140763357611
> Total Training Improvement: 9.25498215618

model.log_probability('ATG')
> -inf

Is there a way around this, or is it expected behavior?

Cheers

**Comment by jmschrei** [comment] 2017-04-03 16:51
This is the expected behavior, because you're saying that in your training data you will never see a G. However, there are ways around it. The simplest would be to include `distribution_inertia=0.25` and `max_iterations=5,` which would make the parameters be a mix of the old and new parameters. You need to set a maximum number of iterations because it'll eventually converge to the new parameters entirely. Another, unimplemented, way of dealing with this is to add pseudocounts to each observation so that you pretend you see each character once, or 0.1 times, or something. It is currently unimplemented because that type of regularization doesn't extend as easily to continuous valued distributions.

**Comment by demodw** [comment] 2017-04-03 16:57
Hm. My intuition would be that, with a pseudocount, the probability should go towards zero, but never be zero. Unless the HMM was trained using the Viterbi algorithm, in which case each position would converge to the observed frequency. 

I might be wrong. I'll have to go skim through the old papers..

**Comment by jmschrei** [comment] 2017-04-03 17:01
Updating a distribution in Baum-Welch is a weighted MLE update, where the weights are determined using the forward-backward algorithm. It is true that the weights tend to never be 0 (excluding structural reasons) but if you only see A and C, no combination of weighting is going to give you weight on a G.

You're currently using a pseudocount on the transition probabilities, not the emissions. Like I said in the above, it would be reasonable to extend that to allow for pseudocounts on the emisisons, but I haven't yet added that.

**Comment by demodw** [comment] 2017-04-03 17:14
Yes, I see. You are right. I might have a stab at it, since I need it explicitly for a categorical hmm.

Cheers.

**Comment by demodw** [comment] 2017-04-04 06:59
Just checking if I'm on the right track. I would need to modify the Distribution object in distributions.pyx to accept a pseudocount for weighting the items, right? 

As far as I've been able to tell the actual update of the emission probabilities happens at line 2998-3000:

> with gil:
>    self.states[k].distribution.from_summaries(
>    inertia=distribution_inertia )

It also seems this is already part of the DirichletDistribution object, so maybe I can just mimick that directly. :-)

**Comment by jmschrei** [comment] 2017-04-13 04:46
Howdy @demodw. Sorry that it took so long to get back to you, some personal issues came up for me, and then I decided to fully fix this issue for you. This has resulted in PR #243 where you can add pseudocounts to all models now during training. For a HMM, this is divided into two types-- pseudocounts on transitions (`transition_pseudocount`), and pseudocounts on emissions (`emission_pseudocount`), or pseudocount for both (`pseudocount`). Currently it only supports uniform pseudocounts over all emission symbols or all components, which would be satisfactory for now.

Using your example, with an untrained model you get the following output:

```
Sequence: 'ACT'  -- Log Probability: -0.513244900357 -- Path: M1 M2 M3
Sequence: 'GGC'  -- Log Probability: -11.0481012413 -- Path: I0 I0 D1 M2 D3
Sequence: 'GAT'  -- Log Probability: -9.12551967402 -- Path: I0 M1 D2 M3
Sequence: 'ACC'  -- Log Probability: -5.08795587886 -- Path: M1 M2 M3
```

You had an issue in your example. `['ATC']*10000` produces a list with 10000 instances of the symbol 'ATC', which is not one of the nucleotides. The appropriate way to generate a bunch of A-T-C sequences is `[['A', 'T', 'C']]*10000`. The following code should work:

```
>>> model.fit([['A', 'C', 'T']]*100, pseudocount=1)
Training improvement: 35.2946534076
Training improvement: 0.497380202993
Training improvement: 0.0440443847526
Training improvement: 0.00263862019878
Training improvement: 5.3345613793e-06
Training improvement: -4.1412398323e-05
Total Training Improvement: 35.8386805377
>>>
>>> for sequence in map( list, ('ACT', 'GGC', 'GAT', 'ACC') ):
    logp, path = model.viterbi( sequence )
    print "Sequence: '{}'  -- Log Probability: {} -- Path: {}".format(
        ''.join( sequence ), logp, " ".join( state.name for idx, state in path[1:-1] ) )
Sequence: 'ACT'  -- Log Probability: -0.149165936502 -- Path: M1 M2 M3
Sequence: 'GGC'  -- Log Probability: -13.9920415959 -- Path: M1 M2 M3
Sequence: 'GAT'  -- Log Probability: -9.37831115641 -- Path: M1 M2 M3
Sequence: 'ACC'  -- Log Probability: -4.76289637602 -- Path: M1 M2 M3
```

Alternatively, if you want to leave the edges as-is but add a pseudocount to the emissions, you can do the following:

```
>>> model.fit([['A', 'C', 'T']]*100, emission_pseudocount=1)
Training improvement: 41.0721999489
Training improvement: 0.540340809001
Training improvement: 0.0957701663647
Training improvement: 0.0229606478595
Training improvement: 0.00585689099371
Training improvement: 0.0015111653737
Training improvement: 0.000389344591994
Training improvement: 0.000100249449325
Training improvement: 2.58082568791e-05
Training improvement: 6.64380700854e-06
Training improvement: 1.71029341445e-06
Training improvement: 4.40273986158e-07
Training improvement: 1.13337925711e-07
Training improvement: 2.91760535731e-08
Training improvement: 7.5106747488e-09
Training improvement: 1.93342231114e-09
Training improvement: 4.97752949968e-10
Total Training Improvement: 41.7391639777
>>>
>>> for sequence in map( list, ('ACT', 'GGC', 'GAT', 'ACC') ):
    logp, path = model.viterbi( sequence )
    print "Sequence: '{}'  -- Log Probability: {} -- Path: {}".format(
        ''.join( sequence ), logp, " ".join( state.name for idx, state in path[1:-1] ) )
Sequence: 'ACT'  -- Log Probability: -0.0878111469026 -- Path: M1 M2 M3
Sequence: 'GGC'  -- Log Probability: -13.9331726974 -- Path: M1 M2 M3
Sequence: 'GAT'  -- Log Probability: -9.31805218058 -- Path: M1 M2 M3
Sequence: 'ACC'  -- Log Probability: -4.70293166374 -- Path: M1 M2 M3
```

You'll have to pull the latest code from github. Let me know if you run into any further issues!

**Comment by demodw** [comment] 2017-04-17 15:45
That is great, thanks a lot!

**Comment by jmschrei** [comment] 2017-04-17 21:46
I'm going to close this for now. Re-open if there are issues.

**Closed by jmschrei** 2017-04-17 21:46 UTC
