### ISSUE TITLE
[BUG] conda recipe is outdated and leads to 'check_pickle" kwarg error with joblib

### ISSUE THREAD

**Issue by dmalzl** [jmschrei/pomegranate#868] opened 2021-02-02 16:32 UTC
**Describe the bug**
I recently used pomegranate to train HMMs on some data. I installed it via conda and assumed I had the newest version. However, after trying to train the model the error:
```python
TypeError: delayed() got an unexpected keyword argument 'check_pickle'
```
kept popping up. The reason for this was clarified with the help of [@jjerphan](https://github.com/jjerphan) who pointed out that the issue was already fixed in the newest version of pomegranate. Thus, I would just like to ask you to update the conda recipe accordingly for future users.

**To Reproduce**
```
conda install pomegranate
*run any code trying to train HMM in python*
```

Best regards,
Daniel

**Comment by jmschrei** [comment] 2021-02-02 17:53
Thanks for the report. I've never put pomegranate on conda (someone else must have), but I'll look into fixing it.

**Comment by dmalzl** [comment] 2021-02-02 18:23
Ah I see. However, I wanted to leave this here for future references.
Thanks anyway

**Comment by rmcgibbo** [comment] 2021-03-24 17:08
I am seeing the same issue in the builds for nixpkgs: https://nix-cache.s3.amazonaws.com/log/q72n5ydzvjzr3hc9zvv41ypgbhqqaqhz-python3.8-pomegranate-0.11.2.drv.

I believe this is probably caused by this argument being removed from the latest release in one of the pomegranate dependencies, such as joblib.

**Comment by CTyny** [comment] 2021-04-08 16:07
I also use miniconda to manage my packages and just came across the same issue training General Mixture Models (for the first time in a long while). For anyone else stumbling across this problem reverting to joblib 0.17.0 was sufficient to resolve the error for me.

**Comment by jmschrei** [comment] 2023-04-16 06:17
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.

**Closed by jmschrei** 2023-04-16 06:17 UTC
