### ISSUE TITLE
[BUG] (Solved) GeneralMixtureModel.from_samples( ... ) no longer working

### ISSUE THREAD

**Issue by lipinoelbreve** [jmschrei/pomegranate#854] opened 2020-12-17 20:01 UTC
**Solution**
Apparently joblib has released a new version and is bringing issues with the delayed( ) function, used by some pomegranate methods.

Just install joblib with an older version (I'm currently ussing 0.16.0) and everything will be fine I guess

**Describe the bug**
I was working with a GMM of two Log Normal distributions using the .from_samples() method. I've never had any issues until now:

Running at Google Colab, when I tried to fit the GMM (using the from_samples() ), the following error occured:
/usr/local/lib/python3.6/dist-packages/pomegranate/kmeans.pyx in genexpr()
TypeError: delayed() got an unexpected keyword argument 'check_pickle'

The traceback states:
/usr/local/lib/python3.6/dist-packages/pomegranate/gmm.pyx in pomegranate.gmm.GeneralMixtureModel.from_samples()
/usr/local/lib/python3.6/dist-packages/pomegranate/kmeans.pyx in pomegranate.kmeans.Kmeans.fit()
/usr/local/lib/python3.6/dist-packages/pomegranate/kmeans.pyx in genexpr()

As far as I know, gmm.pyx calls kmeans.pyx, which runs the function delayed() imported from the joblib package
This function is called three times in kmeans.pyx, passing the argument check_pickle, but apparently it is not taking it anymore.

To check that the error wasn't related to Colab, I installed pomegranate in a new virtual environment
pip3 install wheel
pip3 install numpy
pip3 install scipy
pip3 install networkx
pip3 install joblib
pip3 install Cython
pip3 install pomegranate

After installing, I tried the following code:

**To Reproduce**
from pomegranate import *
import numpy as np

x = np.array([[2],[1],[1],[5],[10],[20],[100],[50],[60]])
model = GeneralMixtureModel.from_samples(LogNormalDistribution, n_components=2, X=x)

However, I once again ran into the same error as in Colab

If anyone is facing the same issue and finds some way around it please let me know, what confuses me the most is that the same code ran without any problem until yesterday.

**Comment by paulbrodersen** [comment] 2020-12-18 16:55
Same problem, solution works. Thank you so much!

**Comment by paulbrodersen** [comment] 2020-12-18 17:16
I would keep the issue open until the problem is actually fixed, not just worked around.

**Comment by jmschrei** [comment] 2020-12-22 05:08
Darn joblib and their lack of back compatibility. I'll make sure to fix this for the next version. Thanks for keeping it open.

**Comment by jmschrei** [comment] 2021-01-09 22:01
Should be fixed now.

**Closed by jmschrei** 2021-01-09 22:01 UTC
