### ISSUE TITLE
BUG: BayesianNetwork exact structure learning error

### ISSUE THREAD

**Issue by jonmmease** [jmschrei/pomegranate#316] opened 2017-08-23 21:07 UTC
I'm getting an exception when running the exact (A*) bayesian network structure learning algorithm. The snippet below is based on the Tutorial 4b notebook

```.python
from sklearn.datasets import load_digits
import numpy as np
from pomegranate import BayesianNetwork

num_cols = 7
X, y = load_digits(10, True)
X = X > np.mean(X)
X = X[:,:num_cols]
net = BayesianNetwork.from_samples(X, algorithm='exact')
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-72-b02206f8f43c> in <module>()
      7 X = X > np.mean(X)
      8 X = X[:,:num_cols]
----> 9 net = BayesianNetwork.from_samples(X, algorithm='exact')

~/anaconda/envs/python3_general/lib/python3.6/site-packages/pomegranate/BayesianNetwork.pyx in pomegranate.BayesianNetwork.BayesianNetwork.from_samples (pomegranate/BayesianNetwork.c:19201)()

~/anaconda/envs/python3_general/lib/python3.6/site-packages/pomegranate/BayesianNetwork.pyx in pomegranate.BayesianNetwork.discrete_exact_a_star (pomegranate/BayesianNetwork.c:27099)()

~/anaconda/envs/python3_general/lib/python3.6/site-packages/pomegranate/utils.pyx in pomegranate.utils.PriorityQueue.pop (pomegranate/utils.c:2459)()

TypeError: '<' not supported between instances of 'NoneType' and 'tuple'
```

Interestingly, when `num_cols` is 6 or less everything works fine.

Details:
 - Pomegranate 0.7.7 installed from pip
 - OS X
 - Python 3.6

Please let me know if there's anything else you need. Thanks!

**Comment by jmschrei** [comment] 2017-08-23 22:30
That's interesting! Can you try running with `exact-dp` and let me know if that works?

**Comment by jmmease** [comment] 2017-08-24 00:15
Yeah, exact-dp works fine

**Comment by jmmease** [comment] 2017-08-28 19:03
Anyone else able to reproduce this issue?

**Comment by jmschrei** [comment] 2017-08-28 21:02
Sorry for the delay. I'm in a state of constant overload (aka grad school). I will look into this soon and get back to you. Can you use exact-dp until I can evaluate the issue?

**Comment by jmmease** [comment] 2017-08-28 22:28
No apology necessary. This issue isn't holding me up, I was just curious about the reproducibility. Thanks for all of your work on this project!

**Comment by Wesserg** [comment] 2018-05-23 16:02
late on the response, but YES - I have the same issue;)

**Comment by willsilvano** [comment] 2018-07-04 15:16
Hi @jmschrei .

Same issue here.

pomegranate version 0.9.0

But in my case the issue is in "from_structure"

**Comment by jmschrei** [comment] 2018-07-04 16:23
That's weird. Can you post the error you get? `from_structure` shouldn't be calling `from_samples`, it should be calling `fit`

**Comment by willsilvano** [comment] 2018-07-04 16:52
TypeError                                 Traceback (most recent call last)
<ipython-input-20-3b281607eba4> in <module>()
----> 1 model = pome.BayesianNetwork.from_structure(X, structure, state_names=state_names)

pomegranate/BayesianNetwork.pyx in pomegranate.BayesianNetwork.BayesianNetwork.from_structure()

pomegranate/distributions.pyx in pomegranate.distributions.ConditionalProbabilityTable.from_samples()

/opt/conda/lib/python3.6/site-packages/numpy/lib/arraysetops.py in unique(ar, return_index, return_inverse, return_counts)
    212         aux = ar[perm]
    213     else:
--> 214         ar.sort()
    215         aux = ar
    216     flag = np.concatenate(([True], aux[1:] != aux[:-1]))

TypeError: '>' not supported between instances of 'str' and 'NoneType'

**Comment by willsilvano** [comment] 2018-07-04 16:55
The code bellow:

![image](https://user-images.githubusercontent.com/7406991/42288635-ed1728f0-7f91-11e8-8b51-a0cf11d30cc6.png)

**Comment by willsilvano** [comment] 2018-07-05 11:19
The code works in the version 0.7.0.

Can you help me?

**Comment by willsilvano** [comment] 2018-07-11 12:49
The code works in the version 0.7.0.

Can you help me @jmschrei ?

**Comment by jmschrei** [comment] 2018-07-11 22:44
I just pushed a fix for the issue that @jonmmease pointed out. @jonmmease can you pull the latest version and try with the fix? @willsilvano can you check and see if it fixed your issue as well?

**Comment by willsilvano** [comment] 2018-07-12 17:52
Hi @jmschrei ,

![erro](https://user-images.githubusercontent.com/7406991/42650588-2af6e01e-85e3-11e8-9393-12aebda7c49e.png)

**Comment by willsilvano** [comment] 2018-07-23 19:45
Hello @jmschrei !
I've found the cause of error I've posted.
Analysing the `from_samples` method from `ConditionalProbabilityTable` class in the `numpy.unique`, I discover I have **NAN** values in one of my variables.
Fixing the values of my variable the error doesn't occurred anymore.

**Comment by jkleckner** [comment] 2018-08-03 00:14
@willsilvano You might consider closing this then.

**Closed** 2018-08-03 03:16 UTC
