### ISSUE TITLE
More understandable errors

### ISSUE THREAD

**Issue by jachymb** [jmschrei/pomegranate#45] opened 2015-11-12 21:55 UTC
I get error like this:

```
File "pomegranate/BayesianNetwork.pyx", line 72, in pomegranate.BayesianNetwork.BayesianNetwork.bake (pomegranate/BayesianNetwork.c:2681)
KeyError: {
    "weight" : 1.0,
    "name" : "GO:0005488",
    "distribution" : "{\n    \"parameters\" : [\n        {\n            \"false\" : 0.25,\n            \"true\" : 0.75\n        }\n    ],\n    \"frozen\" : false,\n    \"name\" : \"DiscreteDistribution\",\n    \"class\" : \"Distribution\"\n}",
    "class" : "State"
}
```

It's not very understandable and gives no guidance to fix the problem in my network. I think it's poor error reporting.

**Comment by jmschrei** [comment] 2015-11-12 22:37
Can you include your code please?

**Comment by jachymb** [comment] 2015-11-13 00:17
My code is complicated and it's difficult to make a minimal example that would reproduce the error.

But I think I managed to find where the problem is and I believe it's actually a bug in pomegranate. One of my distributions in string representation generated by pomegranate is once:
```
'{\n    "class" : "Distribution",\n    "frozen" : false,\n    "name" : "DiscreteDistribution",\n    "parameters" : [\n        {\n            "0" : 0.6770833333333334,\n            "1" : 0.3229166666666667\n        }\n    ]\n}'
```
But next time it becomes
```
'{\n    "class" : "Distribution",\n    "name" : "DiscreteDistribution",\n    "parameters" : [\n        {\n            "1" : 0.3229166666666667,\n            "0" : 0.6770833333333334\n        }\n    ],\n    "frozen" : false\n}'
```

We can see that it's actally the same distribution, but it has different string representation. It is caused by the fact, that keys in dict have undefined order by default. 

We need to make sure that the string representation used as key is always the same for the same distributions, for example by using sorted() on keys() and items() when generating the string.

**Comment by jachymb** [comment] 2015-11-13 01:55
This is a fixing patch to the problem, please include the changes to the main code.

```
diff --git a/pomegranate/BayesianNetwork.pyx b/pomegranate/BayesianNetwork.pyx
index ef13215..245adca 100644
--- a/pomegranate/BayesianNetwork.pyx
+++ b/pomegranate/BayesianNetwork.pyx
@@ -61,15 +61,18 @@ cdef class BayesianNetwork( Model ):
 			self.graph.add_node( f )
 			self.graph.add_edge( m, f )
 
-			f_mapping[state] = f
-			m_mapping[state] = m
-			d_mapping[state.distribution] = d
+			f_mapping[str(state)] = f
+			m_mapping[str(state)] = m
+			d_mapping[str(state.distribution)] = d
 
 			# Progress the counter by one
 			j += 1
 
 		for a, b in self.edges:
-			self.graph.add_edge( m_mapping[a], f_mapping[b] )
+ 
+			self.graph.add_edge(
+                                m_mapping[str(a)],
+                                f_mapping[str(b)] )
 
 		# Now go back and redirect parent pointers to the appropriate
 		# objects.
@@ -77,7 +80,7 @@ cdef class BayesianNetwork( Model ):
 			d = state.distribution
 			if isinstance( d, ConditionalProbabilityTable ):
 				dist = fa_mapping[d]
-				d.parameters[1] = [ d_mapping[parent] for parent in d.parameters[1] ]
+				d.parameters[1] = [ d_mapping[str(parent)] for parent in d.parameters[1] ]
 				state.distribution = d.joint()
 				state.distribution.parameters[1].append( dist )
 
diff --git a/pomegranate/base.pyx b/pomegranate/base.pyx
index 390d5fd..3d0a7ec 100644
--- a/pomegranate/base.pyx
+++ b/pomegranate/base.pyx
@@ -3,7 +3,7 @@
 
 from .distributions cimport Distribution
 from .utils cimport *
-
+from collections import OrderedDict
 import itertools as it
 import json
 import numpy
@@ -103,13 +103,12 @@ cdef class State( object ):
 		"""
 		Convert this state to JSON format.
 		"""
-
-		return json.dumps( { 
-							    'class' : 'State',
-								'distribution' : None if self.is_silent() else str( self.distribution ),
-								'name' : self.name,
-								'weight' : self.weight  
-							}, separators=(',', ' : ' ), indent=4 )
+		data = OrderedDict()
+		data['class'] = 'State'
+		data['distribution'] = None if self.is_silent() else str( self.distribution )
+		data['name'] = self.name
+		data['weight'] = self.weight
+		return json.dumps(data , separators=(',', ' : ' ), indent=4 )
 
 	@classmethod
 	def from_json( cls, s ):
 cdef class Model( object ):
diff --git a/pomegranate/distributions.pyx b/pomegranate/distributions.pyx
index 30a4217..c3170dc 100644
--- a/pomegranate/distributions.pyx
+++ b/pomegranate/distributions.pyx
@@ -203,13 +203,13 @@ cdef class Distribution:
 
 	def to_json( self ):
 		"""Convert the distribution to JSON format."""
+		data = OrderedDict()
+		data['class'] = 'Distribution'
+		data['name'] = self.name
+		data['parameters'] = self.parameters
+		data['frozen'] = self.frozen
 
-		return json.dumps( {
-								'class' : 'Distribution',
-								'name'  : self.name,
-								'parameters' : self.parameters,
-								'frozen' : self.frozen
-						   }, separators=(',', ' : ' ), indent=4 )
+		return json.dumps(data , separators=(',', ' : ' ), indent=4 )
 
 	@classmethod
 	def from_json( cls, s ):
@@ -2014,7 +2014,7 @@ cdef class ConditionalProbabilityTable( MultivariateDistribution ):
 		values, parents, keys = self.parameters
 		return "\n".join( 
 					"\t".join( map( str, key + (cexp( values[idx] ),) ) )
-							for key, idx in keys.items() ) 
+							for key, idx in sorted(keys.items()) ) 
 
 	def __len__( self ):
 		"""
```

**Comment by jachymb** [comment] 2015-11-13 02:10
Note: It only fixes the error where I needed it for my project. It would be a good idea to sanitize __str__ of other distributions or any other classes that use similar mechanism in this fashion, so it cannot happen to anybody.

**Comment by jmschrei** [comment] 2015-11-13 19:58
Is it possible for you to submit that as a pull request?

**Comment by jachymb** [comment] 2015-11-15 15:35
Turns out this causes errors in predict_proba. Also, the original error was caused by using different instances for the same same distribution, which I am not sure if should be allowed. Still, the error was very cryprtic and it took me a long time to debug.

**Comment by jmschrei** [comment] 2015-11-16 01:25
I'm sorry, but I'm still unclear what the problem is. If you have a patch, please submit a pull request and I'll take a look at it. Otherwise please submit a small reproducible case, so that I can investigate.

**Comment by gnzlo789** [comment] 2016-06-22 14:18
I get the same error message, what I want to do is train a bayesian network, save the states and then restore it, so I don't have to do all the training again. I modified the Monty Hall example so you can reproduce the problems. 
There is also a problem when using to_json - from_json - to_json with a ConditionalProbabilityTable. See the comments in the code for more details.

```python
from pomegranate import *

guest = DiscreteDistribution( { 'A': 1./3, 'B': 1./3, 'C': 1./3 } )
prize = DiscreteDistribution( { 'A': 1./3, 'B': 1./3, 'C': 1./3 } )

_data = [[ 'A', 'A', 'A', 0.0 ],
     [ 'A', 'A', 'B', 0.5 ],
     [ 'A', 'A', 'C', 0.5 ],
     [ 'A', 'B', 'A', 0.0 ],
     [ 'A', 'B', 'B', 0.0 ],
     [ 'A', 'B', 'C', 1.0 ],
     [ 'A', 'C', 'A', 0.0 ],
     [ 'A', 'C', 'B', 1.0 ],
     [ 'A', 'C', 'C', 0.0 ],
     [ 'B', 'A', 'A', 0.0 ],
     [ 'B', 'A', 'B', 0.0 ],
     [ 'B', 'A', 'C', 1.0 ],
     [ 'B', 'B', 'A', 0.5 ],
     [ 'B', 'B', 'B', 0.0 ],
     [ 'B', 'B', 'C', 0.5 ],
     [ 'B', 'C', 'A', 1.0 ],
     [ 'B', 'C', 'B', 0.0 ],
     [ 'B', 'C', 'C', 0.0 ],
     [ 'C', 'A', 'A', 0.0 ],
     [ 'C', 'A', 'B', 1.0 ],
     [ 'C', 'A', 'C', 0.0 ],
     [ 'C', 'B', 'A', 1.0 ],
     [ 'C', 'B', 'B', 0.0 ],
     [ 'C', 'B', 'C', 0.0 ],
     [ 'C', 'C', 'A', 0.5 ],
     [ 'C', 'C', 'B', 0.5 ],
     [ 'C', 'C', 'C', 0.0 ]]

monty = ConditionalProbabilityTable(_data, [guest, prize] )

s1 = State( guest, name="guest" )
s2 = State( prize, name="prize" )
s3 = State( monty, name="monty" )

network = BayesianNetwork( "test" )
network.add_states( [ s1, s2, s3 ] )

network.add_transition( s1, s3 )
network.add_transition( s2, s3 )

network.bake()

data = [[ 'A', 'A', 'A' ],
        [ 'A', 'A', 'A' ],
        [ 'A', 'A', 'A' ],
        [ 'A', 'A', 'A' ],
		[ 'A', 'A', 'A' ],
		[ 'B', 'B', 'B' ],
		[ 'B', 'B', 'C' ],
		[ 'C', 'C', 'A' ],
		[ 'C', 'C', 'C' ],
		[ 'C', 'C', 'C' ],
		[ 'C', 'C', 'C' ],
        [ 'C', 'B', 'A' ]]

network.fit( data )

observations = { 'guest' : 'A', 'prize' : 'B' }
beliefs = map( str, network.predict_proba( observations ) )
print "\n".join( "{}\t{}".format( state.name, belief ) for state, belief in zip( network.states, beliefs ) )

_guest = DiscreteDistribution.from_json(guest.to_json())
_prize = DiscreteDistribution.from_json(prize.to_json())
_monty = ConditionalProbabilityTable.from_json(monty.to_json())

# _s1 = State( _guest, name="_guest" )
# _s2 = State( _prize, name="_prize" )
# _s3 = State( _monty, name="_monty" )
_s1 = State.from_json(s1.to_json())
_s2 = State.from_json(s2.to_json())
_s3 = State.from_json(s3.to_json())

# First problem:
print(_s3) # AttributeError: 'list' object has no attribute 'tolist'
# The problem is the type of the first value of the parameters array (table),
# when keys are given (from_json) it should convert the list to a numpy array.
# This affects ConditionalProbabilityTable and JointProbabilityTable.
# The problem can be solved by adding numpy.array(table)

_network = BayesianNetwork( "test" )
_network.add_states( [ _s1, _s2, _s3 ] )

_network.add_transition( _s1, _s3 )
_network.add_transition( _s2, _s3 )

# Second problem: (comment first problem to reproduce this one)
_network.bake()
# I applied the changes shown by @jachymb in the BayesianNetwork class
# and the problem is fixed.


# Third problem: 
# After changing the BayesianNetwork class some of the tests are failing.
# ValueError: None is not in list
# In this example the problem can be reproduced by commenting the line 
# network.fit( data )
# And as @jachymb, the problem is related to predict_proba.

observations = { 'guest' : 'A', 'prize' : 'B' }
beliefs = map( str, _network.predict_proba( observations ) )
print "\n".join( "{}\t{}".format( state.name, belief ) for state, belief in zip( _network.states, beliefs ) )

print("###########")
_n1 = str(network)
_n2 = str(_network)
print(_n1 == _n2)
```

**Comment by jmschrei** [comment] 2023-04-16 06:21
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.

btw, in the new code, a huge focus was on making errors more understandable and providing human-readable errors for as many issues as possible, in large part because issues like this have been in the back of my mind for years.

**Closed by jmschrei** 2023-04-16 06:21 UTC
Labels: enhancement, v1.0.0
