### ISSUE TITLE
nosetests fails with a segmentation fault

### ISSUE THREAD

**Issue by shpigi** [jmschrei/pomegranate#19] opened 2015-06-23 20:27 UTC
Hi
I cloned the current version (0.2.8) from github and ran `nosetests -w tests/`
The tests end in:
```
................ESegmentation fault (core dumped)
```
My setup is (as python reports it):
```
Python 2.7.9 (default, May 10 2015, 09:08:45) 
[GCC 4.8.2] on linux2

>>> numpy.__version__
'1.10.0.dev0+01c59d6'
>>> cython.__version__
'0.22'
>>> scipy.__version__
'0.15.1'
>>> networkx.__version__
'1.9.1'
>>> matplotlib.__version__
'1.4.3'
```

**Comment by jmschrei** [comment] 2015-06-25 08:12
Are you able to use pomegranate normally?

**Comment by shpigi** [comment] 2015-06-25 11:14
hmm. Good question
Looks like my pomegranate installation is broken
I tried several things (rebuilding pomegranate, reinstalling numpy and cython)
I either get an error simply by importing pomegranate or if Instantiate a `pomegranate.HiddenMarkovModel()`

This is strange since I was building pomegranate just fine till this version (my branch of pomegranate also stopped working now that I merged it to the head).
pip install pomegranate gets me a 0.2.6 version that works fine. Is there a reason pypi wasn't updated with this version? 
Any idea what's wrong?

Thanks,
Lavi

**Comment by jmschrei** [comment] 2015-06-25 11:40
Can you post the full error message you receive?

New commits have not been added to PyPi because I am working on training for Bayesian networks, and want to finish that before I put the next version on it. I am having trouble working on pomegranate now because my laptop does not have a working version of MinGW, and my home desktop did since old versions of Anaconda came with MinGW with it.

**Comment by shpigi** [comment] 2015-06-25 12:13
Regarding a C compiler, I would suggest you install the free compiler from Microsoft:
https://www.microsoft.com/en-us/download/details.aspx?id=44266
(This works for python 2.7. I don't know about python 3)

Right now, running `python setup.py build` goes smoothly (though there are many warnings about using a deprecated numpy API or variables that are defined but not used).
Instantiating an HMM fails:
```
In [1]: from pomegranate import *

In [2]: d=NormalDistribution(0,1)

In [3]: s=State(NormalDistribution(0,1),'hi')

In [4]: m=HiddenMarkovModel()
Segmentation fault (core dumped)
```

In and earlier state of the system I got an error on importing pomegranate:
`"Building module pomegranate.base failed: ['ValueError: numpy.dtype has the wrong size, try recompiling "`. I'll post the full error if I get the system back in that state.

**Comment by jmschrei** [comment] 2015-06-25 12:31
Ah. You need to delete the temporary build cython makes when you compile it. For me this is located at C:\Users\Jacob\.pyxbuild\temp.win-amd64-2.7\Release\pyrex\pomegranate. Delete that file, and it should fix the error.

**Comment by shpigi** [comment] 2015-06-25 13:07
Nice to know. Didn't realize cython may be leaving stuff behind..

Anyway, I think I found the problem causing the Segmentation fault.
It was the addition of the following lines to `State.__init__():`
```
		# Bind the distribution to this state
		self.distribution.name = name
```
When the HMM start state is initialized with None as it's distribution, reaching this line crashes the code.
By the way, wouldn't this mess with the option for distribution tying?  I thought that I could provide the same distribution for several (HMM) states and thus enforce their distribution to be the same. This feature is very useful for what I am doing (with auto-regressive HMMs).

Giving the state name to the distribution during state initialization seems to assume that the distribution belongs to a single state. 
Was I using it wrong?

**Comment by jmschrei** [comment] 2015-06-25 13:10
No, you're using it correctly. It's more that I needed a unique identifier for distributions for Bayesian networks, and since the name of distributions was pretty much an unused attribute, I decided to use it there. It should have no influence on HMMs. I remember having, and resolving this issue on my computer, but I can't remember what the resolution was. I'll look into it.

**Comment by shpigi** [comment] 2015-06-25 13:16
great, thanks.
It'd be good to support distribution tying for BNs as well. In fact, when I'm through with ARHMMs (soon) I want to see about using Pomegranate fro general DBNs and I thought your BN code may come in handy for that. There would be lots of distribution tying :)
Could you possibly support dists tying in BNs?

**Comment by jmschrei** [comment] 2015-06-25 13:27
Distribution tying for BNs should be trivial.

The bigger issue for me is time, as I want to do all the things and only have time for some of the things.  :(

**Comment by shpigi** [comment] 2015-06-25 13:41
I perfectly understand time issues. No worries.

Was just a bit concerned because if it is assumed in the package that one distribution can belong to several states then I'm not sure I understand this assignment of the state name to the distribution. 

If this name assignment is done simply because a unique distribution ID is needed in the context of a BN, perhaps just add an ID field and assign some random ID (or the state name) to it in initialization? Just saying...

**Comment by shpigi** [comment] 2015-06-25 14:05
Just found another issue with changing the distribution name: 
The name is used (by eval) to generate the distribution in `from_json()`

Here is what happens now:
```
In [4]: s=State(NormalDistribution(0,1),'hi')

In [5]: s.to_json()
Out[5]: '{\n    "distribution" : "{\\n    \\"frozen\\" : false,\\n    \\"class\\" : \\"Distribution\\",\\n    \\"parameters\\" : [\\n        0,\\n        1\\n    ],\\n    \\"name\\" : \\"hi\\"\\n}",\n    "class" : "State",\n    "weight" : 1.0,\n    "name" : "hi"\n}'

In [6]: s.from_json( s.to_json())
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-5279fe7f9418> in <module>()
----> 1 s.from_json( s.to_json())

/home/lavi/tmp/pomegranate/pomegranate/pomegranate/base.pyx in pomegranate.base.State.from_json (/home/lavi/.pyxbld/temp.linux-x86_64-2.7/pyrex/pomegranate/base.c:3685)()
    142 
    143                 # Otherwise it has a distribution, so decode that
--> 144 		return cls( Distribution.from_json( d['distribution'] ),
    145 					name=str(d['name']), weight=d['weight'] )
    146 

/home/lavi/tmp/pomegranate/pomegranate/pomegranate/distributions.pyx in pomegranate.distributions.Distribution.from_json (/home/lavi/.pyxbld/temp.linux-x86_64-2.7/pyrex/pomegranate/distributions.c:5453)()
    219                         raise SyntaxError( "Distribution object attempting to read invalid object." )
    220 
--> 221                 dist = eval( "{}( [0], 0 )".format( d['name'] ) )
    222                 dist.parameters = d['parameters']
    223                 dist.frozen = d['frozen']

/home/lavi/.pyxbld/lib.linux-x86_64-2.7/pomegranate/distributions.so in <module>()

NameError: name 'hi' is not defined
```

**Comment by shpigi** [comment] 2015-06-25 14:10
Having removed those name-replacing lines, nosetests returns with 5 errors:

```
lavi@ubu-lavi:~/.../pgm/code/pomegranate$ nosetests -w tests/
................E...Exception SyntaxError: SyntaxError('No edges leaving state 10 with key 25',) in 'pomegranate.fsm.FiniteStateMachine._step' ignored
Exception SyntaxError: SyntaxError('No edges leaving state 25 with key 25',) in 'pomegranate.fsm.FiniteStateMachine._step' ignored
..................EEEE.............
======================================================================
ERROR: Test based on the Monty Hall simulation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lavi/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/lavi/work/IBM_Work/PGMtool/lavi/pgm/code/pomegranate/tests/test_distributions.py", line 533, in test_monty
    monty.from_sample( data, weights=[1, 1, 3, 3, 1, 1, 3, 7, 1, 1, 1, 1] )
  File "pomegranate/distributions.pyx", line 2406, in pomegranate.distributions.ConditionalProbabilityTable.from_sample (/home/lavi/.pyxbld/temp.linux-x86_64-2.7/pyrex/pomegranate/distributions.c:40668)
    else:
ValueError: Buffer dtype mismatch, expected 'int' but got 'long'

======================================================================
ERROR: Test the monty distribution before and after training.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lavi/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/lavi/work/IBM_Work/PGMtool/lavi/pgm/code/pomegranate/tests/test_huge_monty_hall.py", line 145, in test_monty
    network.train( data )
  File "pomegranate/BayesianNetwork.pyx", line 181, in pomegranate.BayesianNetwork.BayesianNetwork.train (/home/lavi/.pyxbld/temp.linux-x86_64-2.7/pyrex/pomegranate/BayesianNetwork.c:4602)
    idx = [ indices[ dist.name ] for dist in state.distribution.parameters[1] ] + [i]
KeyError: 'DiscreteDistribution'

======================================================================
ERROR: Test the friend distribution before and after training.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lavi/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/lavi/work/IBM_Work/PGMtool/lavi/pgm/code/pomegranate/tests/test_huge_monty_hall.py", line 173, in test_friend
    network.train( data )
  File "pomegranate/BayesianNetwork.pyx", line 181, in pomegranate.BayesianNetwork.BayesianNetwork.train (/home/lavi/.pyxbld/temp.linux-x86_64-2.7/pyrex/pomegranate/BayesianNetwork.c:4602)
    idx = [ indices[ dist.name ] for dist in state.distribution.parameters[1] ] + [i]
KeyError: 'DiscreteDistribution'

======================================================================
ERROR: Test the remaining distribution before and after training.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lavi/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/lavi/work/IBM_Work/PGMtool/lavi/pgm/code/pomegranate/tests/test_huge_monty_hall.py", line 202, in test_remaining
    network.train( data )
  File "pomegranate/BayesianNetwork.pyx", line 181, in pomegranate.BayesianNetwork.BayesianNetwork.train (/home/lavi/.pyxbld/temp.linux-x86_64-2.7/pyrex/pomegranate/BayesianNetwork.c:4602)
    idx = [ indices[ dist.name ] for dist in state.distribution.parameters[1] ] + [i]
KeyError: 'DiscreteDistribution'

======================================================================
ERROR: Test the prize distribution.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lavi/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/lavi/work/IBM_Work/PGMtool/lavi/pgm/code/pomegranate/tests/test_huge_monty_hall.py", line 232, in test_prize
    network.train( data )
  File "pomegranate/BayesianNetwork.pyx", line 181, in pomegranate.BayesianNetwork.BayesianNetwork.train (/home/lavi/.pyxbld/temp.linux-x86_64-2.7/pyrex/pomegranate/BayesianNetwork.c:4602)
    idx = [ indices[ dist.name ] for dist in state.distribution.parameters[1] ] + [i]
KeyError: 'DiscreteDistribution'

----------------------------------------------------------------------
Ran 55 tests in 0.384s

FAILED (errors=5)
'''

**Comment by jmschrei** [comment] 2015-06-25 15:51
These make sense. to_json is not tested in the unit tests yet, and the name is currently required by the Bayesian Network.

**Comment by jmschrei** [comment] 2015-06-29 07:49
I am unable to reproduce this problem on either a windows or Ubuntu 64 bit machines, using the latest packages on pip. I did find some other casting issues on the Ubuntu client, but those should be resolved momentarily. 

```
numpy v1.9.2
scipy v0.15.1
cython v0.22.1
```

Can you try making a virtual environment with just the requirements, and seeing if it works?

**Comment by jmschrei** [comment] 2015-06-29 08:16
I can reproduce the error using the Anaconda distribution, but not on a minimal virtual environment of just numpy, scipy, cython, matplotlib, and networkx.

**Comment by jmschrei** [comment] 2015-06-29 08:48
Issue should be resolved. Reopen if not!

**Closed** 2015-06-29 13:25 UTC
