### ISSUE TITLE
Model.predict() gives only minus ones

### ISSUE THREAD

**Issue by mhavu** [jmschrei/pomegranate#1003] opened 2022-11-06 14:27 UTC
I am new to pomegranate, and I want to build a HMM with two hidden states. I have labels, and a sequence of series of observations, most of which come from a multinomial distribution (_k = 4, n = 60_). (There is also one that comes from a wrapped normal distribution—see issue #1002—but it can be forgotten for now.) Any calls to `predict()` result in just a list of minus ones, and sometimes the warning "Sequence is impossible":
```python
import numpy as np
from pomegranate import HiddenMarkovModel, DirichletDistribution

# label = np.array([0, 0, 0, ..., 1, 1, 1])
# data = np.array([[60, 0, 0, 0], [58, 2, 0, 0], ...])
dists = [DirichletDistribution.from_samples(data[np.where(label == 0)]),
         DirichletDistribution.from_samples(data[np.where(label == 1)])]
trans_mat = np.array([[0.999, 0.001],
                      [0.002, 0.998]])
starts = np.array([0.5, 0.5])
model = HiddenMarkovModel.from_matrix(trans_mat, dists, starts)
model.predict(data)
# [-1, -1, -1, ...]
```

What am I missing here? (If I create the model with `HiddenMarkovModel.from_samples()` instead, `predict()`, `fit()`, etc. result in a segfault, but I didn't file a bug report yet, since I think I am just doing something wrong.

**Comment by jmschrei** [comment] 2022-11-06 16:19
The issue is that my implementation of dirichlet distributions is wrong and bad. I am currently rewriting pomegranate using torch and fixing this issue, among several others. For now, please avoid the DirichletDistribution implementation.

**Comment by mhavu** [comment] 2022-11-07 11:59
What would you recommend for multinomial distribution instead?

**Comment by jmschrei** [comment] 2022-11-07 15:59
Is your data categories or is it probability vectors over classes? If the data are categories, i.e., integers specifying class, you should use `DiscreteDistribution`.

**Comment by mhavu** [comment] 2022-11-07 17:55
It's probability vectors over classes.

**Comment by mhavu** [comment] 2022-12-18 19:39
According to #458, it is not possible to mix `DiscreteDistribution` with any other type of distribution in `IndependentComponentsDistribution`. Is there a type of distribution in pomegranate I could use for probability vectors over classes?

**Comment by jmschrei** [comment] 2023-04-16 06:07
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.

**Closed by jmschrei** 2023-04-16 06:07 UTC
