### ISSUE TITLE
Exception ignored in HMM supervised training: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'

### ISSUE THREAD

**Issue by ishouldbedany** [jmschrei/pomegranate#369] opened 2017-12-17 23:52 UTC
Hi. Thanks for pomegranate, great library!

Here's my issue. I have multi-dimensional (12 observable emissions for each timepoint) sequential data, with their ground truth labels - 5 hidden states. I am splitting the multidimensional sequences by label and, for each, I model the emission probabilities as a `MultivariateGaussianDistribution`, i.e.:

`states[0] = State(MultivariateGaussianDistribution.from_samples(label_emissions), name="state0")`

After that, I convert my labels (vector of `ints`) to a vector of state names, i.e., `['state1', 'state2', 'state3'].` **Documentation is not very clear regarding this**: at first I thought a vector of `State` objects was required - but I was only able to make it work using state names. 

I then initialize my HMM model, estimating initial probabilities and transition matrices from the training data, using: 

`hmm = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, num_labels, training_data, labels=labels_State_names, algorithm='labeled', name="MyHMM")`

`training_data` is a list of `np.array`, and `labels_State_names` a list of State names' lists. 

Running the above command outputs: 
```
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
KeyError: ('state1',)
KeyError: 'state1'
```

The model is returned nonetheless, **but prediction results on test data and the calculated transition matrix make no sense**. One of `model.start`/`model.end` even has transition probabilities bigger > 0, when they never appear in data nor did I manually add transitions (I was expecting them to be silent). 

Am I missing some **critical step in building my supervised HMM or misunderstanding something?** Thanks!

**Comment by jmschrei** [comment] 2017-12-25 03:41
Howdy, sorry for taking a bit to get to this. You should be able to pass in a list of state names (strings). Is it possible for you to give me a minimally reproducing example for this? It'd make it much faster for me to debug the issue for you! If you use Baum-Welch with no labels, are you getting reasonable (if perhaps not optimal) results?

**Comment by ishouldbedany** [comment] 2017-12-27 14:53
@jmschrei In the meantime, I was able to find my mistake: I was not assigning labels and state names equivalently (labels would go from 1-5, state from 0-4). Results made sense and slightly improved after correcting that, but performance is still very bad. At the moment I think it's more because of the data and the distributions I'm assuming rather than me using `pomegranate` in a wrong way. 

Still, I think the documentation could be a bit more explicit on the format of the labels vectors and on how state names are automatically named. Thanks for the help. Should I close the issue? 

I can try and reproduce #355, but probably better if I post my results there.

**Comment by jmschrei** [comment] 2017-12-27 17:50
Ah, great. I think the best thing is to close this issue and open a new one prodding me to make the documentation better, so that when I scan through the issues it reminds me. Since #355 remains an issue, I'll be looking at it shortly.

**Closed** 2017-12-27 18:06 UTC
