### ISSUE TITLE
TypeError: Object of type 'float32' is not JSON serializable

### ISSUE THREAD

**Issue by williamabrwolf** [jmschrei/pomegranate#552] opened 2019-02-16 18:36 UTC
Getting the following error when trying to fit your HMM.

```
dists = [NormalDistribution(m, sd) for m in mu]
trans_mat = A.numpy()
starts = pi.numpy()
their_model = HiddenMarkovModel.from_matrix(trans_mat, dists, starts)

their_model.fit(np.random.randn(5, 10))
```

gives me

```---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/conda/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/conda/lib/python3.6/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    400                         if cls is not object \
    401                                 and callable(cls.__dict__.get('__repr__')):
--> 402                             return _repr_pprint(obj, self, cycle)
    403 
    404             return _default_pprint(obj, self, cycle)

~/conda/lib/python3.6/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    695     """A pprint that just redirects to the normal repr function."""
    696     # Find newlines and replace them with p.break_()
--> 697     output = repr(obj)
    698     for idx,output_line in enumerate(output.splitlines()):
    699         if idx:

pomegranate/base.pyx in pomegranate.base.Model.__repr__()

pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel.to_json()

~/conda/lib/python3.6/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    236         check_circular=check_circular, allow_nan=allow_nan, indent=indent,
    237         separators=separators, default=default, sort_keys=sort_keys,
--> 238         **kw).encode(obj)
    239 
    240 

~/conda/lib/python3.6/json/encoder.py in encode(self, o)
    199         chunks = self.iterencode(o, _one_shot=True)
    200         if not isinstance(chunks, (list, tuple)):
--> 201             chunks = list(chunks)
    202         return ''.join(chunks)
    203 

~/conda/lib/python3.6/json/encoder.py in _iterencode(o, _current_indent_level)
    428             yield from _iterencode_list(o, _current_indent_level)
    429         elif isinstance(o, dict):
--> 430             yield from _iterencode_dict(o, _current_indent_level)
    431         else:
    432             if markers is not None:

~/conda/lib/python3.6/json/encoder.py in _iterencode_dict(dct, _current_indent_level)
    402                 else:
    403                     chunks = _iterencode(value, _current_indent_level)
--> 404                 yield from chunks
    405         if newline_indent is not None:
    406             _current_indent_level -= 1

~/conda/lib/python3.6/json/encoder.py in _iterencode_list(lst, _current_indent_level)
    323                 else:
    324                     chunks = _iterencode(value, _current_indent_level)
--> 325                 yield from chunks
    326         if newline_indent is not None:
    327             _current_indent_level -= 1

~/conda/lib/python3.6/json/encoder.py in _iterencode_list(lst, _current_indent_level)
    323                 else:
    324                     chunks = _iterencode(value, _current_indent_level)
--> 325                 yield from chunks
    326         if newline_indent is not None:
    327             _current_indent_level -= 1

~/conda/lib/python3.6/json/encoder.py in _iterencode(o, _current_indent_level)
    435                     raise ValueError("Circular reference detected")
    436                 markers[markerid] = o
--> 437             o = _default(o)
    438             yield from _iterencode(o, _current_indent_level)
    439             if markers is not None:

~/conda/lib/python3.6/json/encoder.py in default(self, o)
    178         """
    179         raise TypeError("Object of type '%s' is not JSON serializable" %
--> 180                         o.__class__.__name__)
    181 
    182     def encode(self, o):

TypeError: Object of type 'float32' is not JSON serializable
```

**Comment by williamabrwolf** [comment] 2019-02-16 18:36
I've tried all of the float conversions, etc.

**Comment by jmschrei** [comment] 2019-02-20 22:39
Howdy

Where do you see that example? That's clearly incorrect. The transition matrix needs to be a matrix, not a single number, and the starts needs to be a vector that is the size of the number of states.

**Comment by williamabrwolf** [comment] 2019-02-20 22:49
@jmschrei 

Hi!

There are 5 states.

`trans_mat` is a matrix of size (5, 5).
`dists` is a list of your Normals of length 5.
`starts` is a list of length 5.

My observations are lists of length 10. I put in 5 of them, figuring this would fit.

What size is fit looking for? A list of floats of arbitrary length?

Thanks!

**Comment by jmschrei** [comment] 2019-02-21 00:22
Oh, derp, I thought those were single numbers.

It looks like the error is actually coming from the serialization aspect, not the creation aspect. Can you try doing `_ = their_model.fit(np.random.randn(5, 10))` and see if that works?

**Comment by williamabrwolf** [comment] 2019-02-21 01:00
Works...

At least doesn't error. No idea how that works? Ha.

OK. How do I interpret the params (that I access via `get_params`)? I just want to compare my transition matrix `A` and distribution over the initial state `pi` with your results.

Is there documentation?

Just trying to add a simple unit test.

**Comment by jmschrei** [comment] 2019-02-21 01:15
It errored because there's an issue with the serialization function (turning the Python object into a string to display to the screen). When you call fit, you get a copy of the object back (so that you can do chaining, like `model.fit(..).predict(..)`). If you don't assign it to a variable, and it's the last line in the cell of a Jupyter notebook (which I assume you're doing), it's going to try displaying the object that gets returned... and erroring. By assigning it to a dummy variable, Jupyter doesn't try displaying the object, and so never calls the serialization function.

You can get the transition matrix via `model.dense_transition_matrix()`. The rows and columns correspond to the same ordering you'll find in `model.states`. If you want the start probabilities, you can just do `model.dense_transition_matrix()[model.start_index]` I think. Let me know if that works.

**Comment by cavaunpeu** [comment] 2019-02-23 02:27
In HMMs, don't we maintain/update a separate vector for the distribution over latent states in the model's first latent node?

**Comment by jmschrei** [comment] 2019-02-23 02:31
Some implementations use a separate vector to hold the start probabilities, but there's no reason that it can't be included in the transition matrix. The start state is included in pomegranate as a hidden state, and so naturally is part of the transition matrix.

**Comment by williamabrwolf** [comment] 2019-02-23 02:44
OK. Also:

<img width="842" alt="screen shot 2019-02-22 at 9 42 57 pm" src="https://user-images.githubusercontent.com/31516733/53280681-032ce880-36eb-11e9-844b-5312ffd504da.png">

What of this?

A tutorial would be helpful. I have no idea what's real anymore with these HMMs 😅 .

**Comment by williamabrwolf** [comment] 2019-02-23 02:45
<img width="909" alt="screen shot 2019-02-22 at 9 45 14 pm" src="https://user-images.githubusercontent.com/31516733/53280689-29528880-36eb-11e9-8d6a-72161c96d712.png">

**Comment by jmschrei** [comment] 2019-02-23 02:56
I'm sorry you're running into issues. There is a tutorial here: https://github.com/jmschrei/pomegranate/blob/master/tutorials/B_Model_Tutorial_3_Hidden_Markov_Models.ipynb and multiple HMM examples in the examples folder.

The fastest way to get help with an issue is to post a minimal reproducing example of your error, preferably with randomly generated data or with your data attached, so that I can toy around with it on my side.

It looks like you're passing in a list of observations to the fit function, when you need to be passing in a list of sequences. You can probably resolve this by passing in `X` rather than `x` to the `fit` function. 

You may find it helpful to look at the documentation if you're having trouble, which can be found on the documentation page here: https://pomegranate.readthedocs.io/en/latest/ or by using the help function, such as `help(their_model.fit)`. You'll get something that starts off like this:

```
fit(...)
    Fit the model to data using either Baum-Welch, Viterbi, or supervised training.
    
    Given a list of sequences, performs re-estimation on the model
    parameters. The two supported algorithms are "baum-welch", "viterbi",
    and "labeled", indicating their respective algorithm. "labeled"
    corresponds to supervised learning that requires passing in a matching
    list of labels for each symbol seen in the sequences.
    
    Training supports a wide variety of other options including using
    edge pseudocounts and either edge or distribution inertia.
    
    Parameters
    ----------
    sequences : array-like
        An array of some sort (list, numpy.ndarray, tuple..) of sequences,
        where each sequence is a numpy array, which is 1 dimensional if
        the HMM is a one dimensional array, or multidimensional if the HMM
        supports multiple dimensions.
```

Let me know if that resolves your issue.

**Comment by williamabrwolf** [comment] 2019-02-23 02:59
Understood re: the `fit` signature.

What of the `log_probability` thing? Why should I have `nan` logprob after fitting the model to the sequence in question?

**Comment by jmschrei** [comment] 2019-02-23 03:02
I'm anticipating that the bug in the fit function is messing up the internals of the model. Try it again with the correct signature, it might work now.

**Comment by williamabrwolf** [comment] 2019-02-23 03:15
What do you mean? The `fit` doesn't error out; I'm calling `log_probability` in the same way I called in the lines previous.

**Comment by jmschrei** [comment] 2019-02-23 04:01
It's difficult for me to say without knowing more about your model. Potentially, one of the components is erroring out. You should try inspecting the model parameters after training to see what they look like.

**Comment by williamabrwolf** [comment] 2019-02-23 04:02
Good point. Will report back. Thanks JMS!

**Closed** 2019-12-04 18:23 UTC
