### ISSUE TITLE
HMM predict documentation not correct

### ISSUE THREAD

**Issue by himat** [jmschrei/pomegranate#245] opened 2017-04-21 01:10 UTC
The [predict documentation](https://github.com/rlcode/reinforcement-learning) says that it returns (logp, path). But when I ran my HMM code, I found that it only returned the state sequence, and only the numbers of the states at that, not even the entire object, like model.viterbi does.

predict returned `[3, 0, 1, 0, 2]` (where I have 3 states in my model)

**Comment by jmschrei** [comment] 2017-04-22 23:55
Good catch. The behavior is the intended behavior, but the documentation is back from when it was equivalent to running `model.viterbi(X)` (which returns (logp, path)). I'll update it soon.

**Comment by jmschrei** [comment] 2017-05-31 16:40
Resolved by @mrshu, thank you both!

**Closed** 2017-05-31 16:40 UTC

**Comment by VertexC** [comment] 2018-06-20 05:20
Hi @jmschrei , is the first 3 in [3, 0, 1, 0, 2] indicates the number of states while the rest is the actual predicted path?

**Comment by jmschrei** [comment] 2018-06-20 18:01
No, each one of the number is an index into `model.states`. Note that this may not be the same order that you added states in due to an internal topological sort. What this specific return is saying is that it begins in state 3 (the hidden start state), then transitions to state 0, then transitions to state 1, then transitions to state 0, then transitions to state 2 (potentially the optional hidden end state). I say potentially because I'm not sure what the architecture of model is. All models contain a hidden start state, and all paths begin there. You'll note that len(model.states) is equal to the number of states you added in +2, the required hidden start state and the optional hidden end state.

Does that clarify things?

**Comment by VertexC** [comment] 2018-06-20 22:43
That helps a lot. I am trying to store the previous trained parameters from HMM. 
If I have K states, can I simply do 
```python
params = [model_train.states[k].distribution for k in range(K)]
```
as i assume the start and end states are always appended at last, and they not not needed if i use from_matrix to initialize the model.
Is my understanding right?
