### ISSUE TITLE
BayesianNetwork to_json then from_json error

### ISSUE THREAD

**Issue by fengyeyou** [jmschrei/pomegranate#305] opened 2017-08-03 08:31 UTC
i use the bayesianNetwork, when the the network is done,  i use model.to_json(), then i use 
BayesianNetwork.from_json( network.to_json() ) to get the network,but it is wrong, i also test in 
bayesnet_monty_hall_train, same error.      plese help .

Traceback (most recent call last):
  File "/home/hadoop/PycharmProjects/sem/test/examples/bayesnet_monty_hall_train.py", line 132, in <module>
    gmm_2 = BayesianNetwork.from_json( network.to_json() )
  File "pomegranate/BayesianNetwork.pyx", line 749, in pomegranate.BayesianNetwork.BayesianNetwork.from_json
  File "pomegranate/BayesianNetwork.pyx", line 283, in pomegranate.BayesianNetwork.BayesianNetwork.bake
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by jmschrei** [comment] 2017-08-03 17:14
What version of pomegranate are you using? You can figure this out with `import pomegranate; print(pomegranate.__version__)`. If it's not 0.7.7, you should upgrade to that first.

**Comment by fengyeyou** [comment] 2017-08-04 02:19
Yes, the version is right, you mean you version can do this ?
>>> import pomegranate
>>> print(pomegranate.__version__)
0.7.7

**Comment by fengyeyou** [comment] 2017-08-04 08:15
I check my version is right, and I also test on my fellow's pc which version is also is 0.7.7, please check this script , thank you very much
[bayesnet_monty_hall_train.txt](https://github.com/jmschrei/pomegranate/files/1199654/bayesnet_monty_hall_train.txt)

**Comment by jmschrei** [comment] 2017-08-04 20:23
After modifying the script slightly at the end, such that the full script reads as follows:

```python
import math
from pomegranate import *

guest = DiscreteDistribution( { 'A': 1./3, 'B': 1./3, 'C': 1./3 } )
prize = DiscreteDistribution( { 'A': 1./3, 'B': 1./3, 'C': 1./3 } )

monty = ConditionalProbabilityTable(
	[[ 'A', 'A', 'A', 0.0 ],
	 [ 'A', 'A', 'B', 0.5 ],
	 [ 'A', 'A', 'C', 0.5 ],
	 [ 'A', 'B', 'A', 0.0 ],
	 [ 'A', 'B', 'B', 0.0 ],
	 [ 'A', 'B', 'C', 1.0 ],
	 [ 'A', 'C', 'A', 0.0 ],
	 [ 'A', 'C', 'B', 1.0 ],
	 [ 'A', 'C', 'C', 0.0 ],
	 [ 'B', 'A', 'A', 0.0 ],
	 [ 'B', 'A', 'B', 0.0 ],
	 [ 'B', 'A', 'C', 1.0 ],
	 [ 'B', 'B', 'A', 0.5 ],
	 [ 'B', 'B', 'B', 0.0 ],
	 [ 'B', 'B', 'C', 0.5 ],
	 [ 'B', 'C', 'A', 1.0 ],
	 [ 'B', 'C', 'B', 0.0 ],
	 [ 'B', 'C', 'C', 0.0 ],
	 [ 'C', 'A', 'A', 0.0 ],
	 [ 'C', 'A', 'B', 1.0 ],
	 [ 'C', 'A', 'C', 0.0 ],
	 [ 'C', 'B', 'A', 1.0 ],
	 [ 'C', 'B', 'B', 0.0 ],
	 [ 'C', 'B', 'C', 0.0 ],
	 [ 'C', 'C', 'A', 0.5 ],
	 [ 'C', 'C', 'B', 0.5 ],
	 [ 'C', 'C', 'C', 0.0 ]], [guest, prize] )

s1 = State( guest, name="guest" )
s2 = State( prize, name="prize" )
s3 = State( monty, name="monty" )

network = BayesianNetwork( "test" )
network.add_states(  s1, s2, s3  )
network.add_transition( s1, s3 )
network.add_transition( s2, s3 )
network.bake()

data = [[ 'A', 'A', 'A' ],
		[ 'A', 'A', 'A' ],
		[ 'A', 'A', 'A' ],
		[ 'A', 'A', 'A' ],
		[ 'A', 'A', 'A' ],
		[ 'B', 'B', 'B' ],
		[ 'B', 'B', 'C' ],
		[ 'C', 'C', 'A' ],
		[ 'C', 'C', 'C' ],
		[ 'C', 'C', 'C' ],
		[ 'C', 'C', 'C' ],
		[ 'C', 'B', 'A' ]]

print(network.log_probability(data).sum())
network.fit( data )
print(network.log_probability(data).sum())
network2 = BayesianNetwork.from_json(network.to_json())
print(network2.log_probability(data).sum())
```

I get the following results:

```
-inf
-28.9045171764
-28.9045171764
```

Can you post a minimally reproducing full example of the code, and try reinstalling pomegranate? It can sometimes get difficult like this.

**Comment by fengyeyou** [comment] 2017-08-07 08:44
I tried reinstalling pomegranate, but it does not work. it is still the error. My fellow also has the problem.
I do not know why.
Traceback (most recent call last):
  File "/home/hadoop/PycharmProjects/sem/test/bayes_sem/test_json.py", line 62, in <module>
    network2 = BayesianNetwork.from_json(network.to_json())
  File "pomegranate/BayesianNetwork.pyx", line 749, in pomegranate.BayesianNetwork.BayesianNetwork.from_json
  File "pomegranate/BayesianNetwork.pyx", line 283, in pomegranate.BayesianNetwork.BayesianNetwork.bake
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by jmschrei** [comment] 2017-08-07 17:11
Can you describe how you re-installed pomegranate? Did you delete all source files (probably in site-packages), confirm that it wasn't installed by trying to import it, and then re-install? Can you describe what type of OS you're on and what did you did to install it? This type of information is necessary, because if I can't reproduce the error I can't fix it.

**Comment by fengyeyou** [comment] 2017-08-08 02:51
My OS is Ubantu 16.04LTS, 64bit. I use python 3.5.2 which the OS own.
I uninstall pomegranate by using sudo pip install pomegranate. and I alse make sure the site-packages has no pomegranate.
Before i reinstall the pomegranate, I use import test. it really none.
I install pomegranate use sudo pip install pomegranate. And I also tried the way below
    git clone https://github.com/jmschrei/pomegranate.git
    cd pomegranate
    python setup.py install
but it doesnot work too. the error is same.

**Comment by handsaway** [comment] 2017-08-14 11:09
Hi Jacob,
I also get the error ` IndexError: index 1 is out of bounds for axis 0 with size 1 `
when using `BayesianNetwork.from_json` since I upgraded pomegranate from 0.7.3 to 0.7.7.
When running the same code using a virtual environment with pomegranate 0.7.3, it works perfectly.

OS: OS X 10.11.6
python 3.6

**Comment by handsaway** [comment] 2017-08-14 13:06
I have also tried the Monty Hall example posted above.
Output using pomegranate 0.7.3:
```
-inf
-28.9045171764
-28.9045171764

Process finished with exit code 0
```
Output using pomegranate 0.7.7:
```
-inf
-28.9045171764
Traceback (most recent call last):
  File "/Users/xxxx/Documents/PycharmProjects/tutorials/tutorialMontyHall.py", line 62, in <module>
    network2 = BayesianNetwork.from_json(network.to_json())
  File "pomegranate/BayesianNetwork.pyx", line 749, in pomegranate.BayesianNetwork.BayesianNetwork.from_json (pomegranate/BayesianNetwork.c:16306)
  File "pomegranate/BayesianNetwork.pyx", line 283, in pomegranate.BayesianNetwork.BayesianNetwork.bake (pomegranate/BayesianNetwork.c:8006)
IndexError: index 1 is out of bounds for axis 0 with size 1

Process finished with exit code 1
```

**Comment by jmschrei** [comment] 2017-08-16 04:22
I can reproduce the error-- I hadn't upgraded to v0.7.7 on the machine I had used to test it. I'm working on it now, hopefully I'll have it fixed in the next few days. Thanks for your patience.

**Comment by jmschrei** [comment] 2017-08-19 23:58
I just pushed a fix to this to the master branch on GitHub. Can you clone it and confirm that it fixes your issue? It is not yet on PyPI.

**Comment by fengyeyou** [comment] 2017-08-22 05:26
I test it, now it is ok. thank you very much.

**Comment by handsaway** [comment] 2017-09-06 13:07
I also tested, both the Monty Hall example and my own project, with the latest pomegranate from master branch: everything works.
Thank you @jmschrei

**Comment by jmschrei** [comment] 2017-09-06 19:57
Great!

**Closed by jmschrei** 2017-09-06 19:57 UTC

**Comment by abs51295** [comment] 2017-11-28 15:07
@jmschrei I am facing the same issue with version 0.8.0. Can you confirm?
